name: Deploy to S3

on:
  push:
    branches:
      - main
      - adarsh_feature   # add more feature branches here if needed yes
      # or use 'feature/*' to autoâ€‘include all feature branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2   # change to your region

      - name: Deploy to S3
        run: |
          echo "Branch detected: ${{ github.ref }}"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to PROD bucket..."
            aws s3 sync . s3://project-scripts-main/ --delete
          elif [ "${{ github.ref }}" == "refs/heads/adarsh_feature" ]; then
            echo "Deploying to TEST bucket/prefix..."
            aws s3 sync . s3://project-scripts-feature/adarsh_feature/ --delete
          fi