<<<<<<< HEAD
name: Deploy to S3
=======
name: Sync scripts to S3
>>>>>>> 2521fa386ca298690674202f2e135aa695cb752e

on:
  push:
    branches:
<<<<<<< HEAD
      - main
      - adarsh_feature   # add more feature branches here if needed
      # or use 'feature/*' to autoâ€‘include all feature branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

=======
      - main   # Run this workflow only when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest   # GitHub provides a Linux runner

    steps:
      # Step 1: Checkout your repo so the runner has access to your files
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using your IAM user keys stored in GitHub Secrets
>>>>>>> 2521fa386ca298690674202f2e135aa695cb752e
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
<<<<<<< HEAD
          aws-region: ap-southeast-2   # change to your region

      - name: Deploy to S3
        run: |
          echo "Branch detected: ${{ github.ref }}"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to PROD bucket..."
            aws s3 sync . s3://production-scripts-practice/ --delete
          elif [ "${{ github.ref }}" == "refs/heads/adarsh_feature" ]; then
            echo "Deploying to TEST bucket/prefix..."
            aws s3 sync . s3://branch-specific-scripts/adarsh_feature/ --delete
          fi
=======
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Sync the scripts folder to your S3 bucket
      - name: Sync scripts folder to S3
        run: aws s3 sync project-dataprocessing/scripts s3://${{ secrets.S3_BUCKET }}/scripts --delete 
>>>>>>> 2521fa386ca298690674202f2e135aa695cb752e
